//! Release tooling only. Never included in the shipped application.
use base64::{engine::general_purpose::STANDARD, Engine};
use minisign_verify::{PublicKey, Signature};

/// Tauri stores the complete minisign public key and signature as base64 text.
/// Use the same verifier/options as the official updater. No private key read.
pub fn verify(
    data: &[u8],
    public_key: &str,
    signature: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let public_key = String::from_utf8(STANDARD.decode(public_key.trim())?)?;
    let signature = String::from_utf8(STANDARD.decode(signature.trim())?)?;
    PublicKey::decode(&public_key)?.verify(data, &Signature::decode(&signature)?, true)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    // Public fixture from minisign-verify's published documentation. No private
    // signing key is present here or generated by these tests.
    const KEY: &str = "untrusted comment: public test fixture\nRWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3";
    const SIGNATURE: &str = "untrusted comment: signature from minisign secret key\nRUQf6LRCGA9i559r3g7V1qNyJDApGip8MfqcadIgT9CuhV3EMhHoN1mGTkUidF/z7SrlQgXdy8ofjb7bNJJylDOocrCo8KLzZwo=\ntrusted comment: timestamp:1633700835\tfile:test\tprehashed\nwLMDjy9FLAuxZ3q4NlEvkgtyhrr0gtTu6KC4KBJdITbbOeAi1zBIYo0v4iTgt8jJpIidRJnp94ABQkJAgAooBQ==";
    #[test]
    fn official_public_fixture_verifies() {
        verify(b"test", &STANDARD.encode(KEY), &STANDARD.encode(SIGNATURE)).unwrap();
    }
    #[test]
    fn changed_artifact_or_signature_is_rejected() {
        assert!(verify(
            b"tampered",
            &STANDARD.encode(KEY),
            &STANDARD.encode(SIGNATURE)
        )
        .is_err());
        let bad = SIGNATURE.replace("RUQf", "RUQg");
        assert!(verify(b"test", &STANDARD.encode(KEY), &STANDARD.encode(bad)).is_err());
        assert!(verify(b"test", "", &STANDARD.encode(SIGNATURE)).is_err());
    }
}
